# Generated by Django 2.0 on 2020-01-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='first_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
